key: buildings_energy_supply
groups:
  - header: buildings_local_production
    items:
      - key: input_buildings_solar_pv_demand
        unit: 'TJ'
      - key: buildings_final_demand_solar_thermal_demand
        unit: 'TJ'
