key: buildings_advanced
groups:
  - header: buildings_electricity_distribution
    type: slider
    items:
      - key: buildings_final_demand_electricity_buildings_final_demand_for_lighting_electricity_parent_share
        unit: '%'
      - key: buildings_final_demand_electricity_buildings_final_demand_for_space_heating_electricity_parent_share
        unit: '%'
      - key: buildings_final_demand_electricity_buildings_final_demand_for_appliances_electricity_parent_share
        unit: '%'
      - key: buildings_final_demand_electricity_buildings_final_demand_for_cooling_electricity_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_network_gas_distribution
    type: slider
    items:
      - key: buildings_final_demand_network_gas_buildings_final_demand_for_appliances_network_gas_parent_share
        unit: '%'
      - key: buildings_final_demand_network_gas_buildings_final_demand_for_space_heating_network_gas_parent_share
        unit: '%'
      - key: buildings_final_demand_network_gas_buildings_final_demand_for_cooling_network_gas_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_wood_pellets_distribution
    type: slider
    items:
      - key: buildings_final_demand_wood_pellets_buildings_final_demand_for_space_heating_wood_pellets_parent_share
        unit: '%'
      - key: buildings_final_demand_wood_pellets_buildings_final_demand_for_appliances_wood_pellets_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_coal_distribution
    type: slider
    items:
      - key: buildings_final_demand_coal_buildings_final_demand_for_space_heating_coal_parent_share
        unit: '%'
      - key: buildings_final_demand_coal_buildings_final_demand_for_appliances_coal_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_crude_oil_distribution
    type: slider
    items:
      - key: buildings_final_demand_crude_oil_buildings_final_demand_for_space_heating_crude_oil_parent_share
        unit: '%'
      - key: buildings_final_demand_crude_oil_buildings_final_demand_for_appliances_crude_oil_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_network_gas_space_heating_distribution
    type: slider
    items:
      - key: buildings_final_demand_for_space_heating_network_gas_buildings_space_heater_heatpump_air_water_network_gas_parent_share
        unit: '%'
      - key: buildings_final_demand_for_space_heating_network_gas_buildings_space_heater_network_gas_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_electricity_space_heating_distribution
    type: slider
    items:
      - key: buildings_final_demand_for_space_heating_electricity_buildings_space_heater_collective_heatpump_water_water_ts_electricity_parent_share
        unit: '%'
      - key: buildings_final_demand_for_space_heating_electricity_buildings_space_heater_electricity_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_electricity_lighting_distribution
    type: slider
    items:
      - key: buildings_final_demand_for_lighting_electricity_buildings_lighting_efficient_fluorescent_electricity_parent_share
        unit: '%'
      - key: buildings_final_demand_for_lighting_electricity_buildings_lighting_standard_fluorescent_electricity_parent_share
        unit: '%'
      - key: buildings_final_demand_for_lighting_electricity_buildings_lighting_led_electricity_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: buildings_electricity_cooling_distribution
    type: slider
    items:
      - key: buildings_final_demand_for_cooling_electricity_buildings_cooling_airconditioning_electricity_parent_share
        unit: '%'
      - key: buildings_final_demand_for_cooling_electricity_buildings_cooling_collective_heatpump_water_water_ts_electricity_parent_share
        unit: '%'
        flexible: true
        skip_validation: true
