key: area_emission_factors
groups:
  - header: area_emission_factors
  - header: area_emission_factors_general
    items:
    - key: file_carriers_natural_gas_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_crude_oil_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_coal_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_lignite_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_non_biogenic_waste_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
  - header: area_emission_factors_transport_fuels
    items:
    - key: file_carriers_diesel_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_gasoline_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_heavy_fuel_oil_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_kerosene_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_lng_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_lpg_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
  - header: area_emission_factors_import
    items:
    - key: file_carriers_imported_electricity_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_imported_heat_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_imported_hydrogen_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4
    - key: file_carriers_imported_ammonia_co2_conversion_per_mj
      unit: 'kg/MJ'
      precision: 4

