key: industry_other

groups:
  - header: industry_other_energetic
    items:
      - key: input_industry_other_electricity_demand
        unit: 'TJ'
        entso: |
          EB("Final consumption - industry sector - energy use", "Electricity") +
          EB("Energy sector - electricity and heat generation - energy use", "Electricity") +
          EB("Energy sector - coke ovens - energy use", "Electricity") +
          EB("Energy sector - blast furnaces - energy use", "Electricity") +
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Electricity") -
          EB("Final consumption - industry sector - iron and steel - energy use", "Electricity") -
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Electricity") -
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Electricity") -
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Electricity") -
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Electricity") -
          EB("Energy sector - energy use", "Electricity")
      - key: input_industry_other_network_gas_demand
        unit: 'TJ'
        entso: |
          EB("Final consumption - industry sector - energy use", "Network gas") +
          EB("Energy sector - electricity and heat generation - energy use", "Network gas") +
          EB("Energy sector - coke ovens - energy use", "Network gas") +
          EB("Energy sector - blast furnaces - energy use", "Network gas") +
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Network gas") -
          EB("Final consumption - industry sector - iron and steel - energy use", "Network gas") -
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Network gas") -
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Network gas") -
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Network gas") -
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Network gas") -
          EB("Energy sector - energy use", "Network gas")
      - key: input_industry_other_steam_hot_water_demand
        unit: 'TJ'
        entso: |
          EB("Final consumption - industry sector - energy use", "Heat") +
          EB("Energy sector - electricity and heat generation - energy use", "Heat") +
          EB("Energy sector - coke ovens - energy use", "Heat") +
          EB("Energy sector - blast furnaces - energy use", "Heat") +
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Heat") -
          EB("Final consumption - industry sector - iron and steel - energy use", "Heat") -
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Heat") -
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Heat") -
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Heat") -
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Heat") -
          EB("Energy sector - energy use", "Heat")
      - key: input_industry_other_wood_pellets_demand
        unit: 'TJ'
        entso: |
          EB("Final consumption - industry sector - energy use", "Primary solid biofuels") +
          EB("Energy sector - electricity and heat generation - energy use", "Primary solid biofuels") +
          EB("Energy sector - coke ovens - energy use", "Primary solid biofuels") +
          EB("Energy sector - blast furnaces - energy use", "Primary solid biofuels") +
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Primary solid biofuels") -
          EB("Final consumption - industry sector - iron and steel - energy use", "Primary solid biofuels") -
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Primary solid biofuels") -
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Primary solid biofuels") -
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Primary solid biofuels") -
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Primary solid biofuels") -
          EB("Energy sector - energy use", "Primary solid biofuels")
      - key: input_industry_other_crude_oil_demand
        unit: 'TJ'
        entso: |
          EB("Final consumption - industry sector - energy use", "Crude oil aggregated") +
          EB("Energy sector - electricity and heat generation - energy use", "Crude oil aggregated") +
          EB("Energy sector - coke ovens - energy use", "Crude oil aggregated") +
          EB("Energy sector - blast furnaces - energy use", "Crude oil aggregated") +
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Crude oil aggregated") -
          EB("Final consumption - industry sector - iron and steel - energy use", "Crude oil aggregated") -
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Crude oil aggregated") -
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Crude oil aggregated") -
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Crude oil aggregated") -
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Crude oil aggregated") -
          EB("Energy sector - energy use", "Crude oil aggregated")
      - key: input_industry_other_coal_demand
        unit: 'TJ'
        entso: |
          EB("Final consumption - industry sector - energy use", "Coal") +
          EB("Energy sector - electricity and heat generation - energy use", "Coal") +
          EB("Energy sector - coke ovens - energy use", "Coal") +
          EB("Energy sector - blast furnaces - energy use", "Coal") +
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Coal") -
          EB("Final consumption - industry sector - iron and steel - energy use", "Coal") -
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Coal") -
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Coal") -
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Coal") -
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Coal") -
          EB("Energy sector - energy use", "Coal") -
          EB("Final consumption - industry sector - energy use", "Coke oven coke") -
          EB("Energy sector - electricity and heat generation - energy use", "Coke oven coke") -
          EB("Energy sector - coke ovens - energy use", "Coke oven coke") -
          EB("Energy sector - blast furnaces - energy use", "Coke oven coke") -
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Coke oven coke") +
          EB("Final consumption - industry sector - iron and steel - energy use", "Coke oven coke") +
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Coke oven coke") +
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Coke oven coke") +
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Coke oven coke") +
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Coke oven coke") +
          EB("Energy sector - energy use", "Coke oven coke")
      - key: input_industry_other_cokes_demand
        unit: 'TJ'
        entso: |
          EB("Final consumption - industry sector - energy use", "Coke oven coke") +
          EB("Energy sector - electricity and heat generation - energy use", "Coke oven coke") +
          EB("Energy sector - coke ovens - energy use", "Coke oven coke") +
          EB("Energy sector - blast furnaces - energy use", "Coke oven coke") +
          EB("Energy sector - petroleum refineries (oil refineries) - energy use", "Coke oven coke") -
          EB("Final consumption - industry sector - iron and steel - energy use", "Coke oven coke") -
          EB("Final consumption - industry sector - chemical and petrochemical - energy use", "Coke oven coke") -
          EB("Final consumption - industry sector - non-ferrous metals - energy use", "Coke oven coke") -
          EB("Final consumption - industry sector - food, beverages and tobacco - energy use", "Coke oven coke") -
          EB("Final consumption - industry sector - paper, pulp and printing - energy use", "Coke oven coke") -
          EB("Energy sector - energy use", "Coke oven coke")

  - header: industry_other_non_energetic
    items:
      - key: input_industry_other_network_gas_non_energetic_demand
        unit: 'TJ'
#        entso: |
#          EB("Final consumption - industry sector - other - non-energy use", "Network gas")
      - key: input_industry_other_wood_pellets_non_energetic_demand
        unit: 'TJ'
#        entso: |
#          EB("Final consumption - industry sector - other - non-energy use", "Primary solid biofuels")
      - key: input_industry_other_crude_oil_non_energetic_demand
        unit: 'TJ'
#        entso: |
#          EB("Final consumption - industry sector - other - non-energy use", "Crude oil aggregated")
      - key: input_industry_other_coal_non_energetic_demand
        unit: 'TJ'
#        entso: |
#          EB("Final consumption - industry sector - other - non-energy use", "Coal") -
#          EB("Final consumption - industry sector - other - non-energy use", "Coke oven coke")
      - key: input_industry_other_cokes_non_energetic_demand
        unit: 'TJ'
#        entso: |
#          EB("Final consumption - industry sector - other - non-energy use", "Coke oven coke")
