key: industry_metal

groups:
  - header: industry_metal_steel
    type: slider
    items:
      - key: input_industry_metal_steel_scaling_factor
        unit: '%'

  - header: industry_metal_aluminium
    type: slider
    items:
      - key: input_industry_metal_aluminium_scaling_factor
        unit: '%'

  - header: industry_metal_other
    items:
      - key: input_industry_metal_other_electricity_demand
        unit: 'TJ'
      - key: input_industry_metal_other_network_gas_demand
        unit: 'TJ'
      - key: input_industry_metal_other_steam_hot_water_demand
        unit: 'TJ'
      - key: input_industry_metal_other_wood_pellets_demand
        unit: 'TJ'
      - key: input_industry_metal_other_crude_oil_demand
        unit: 'TJ'
      - key: input_industry_metal_other_coal_demand
        unit: 'TJ'