key: industry_chemical

groups:
  - header: industry_chemical_fertilizers
    items:
      - key: input_industry_chemical_fertilizers_scaling_factor
        unit: '%'
  - header: industry_chemical_refineries
    items:
      - key: input_industry_chemical_refineries_scaling_factor
        unit: '%'
  - header: industry_chemical_other
    items:
      - key: input_industry_chemical_other_electricity_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_network_gas_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_steam_hot_water_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_wood_pellets_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_crude_oil_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_coal_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_network_gas_non_energetic_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_wood_pellets_non_energetic_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_crude_oil_non_energetic_demand
        unit: 'TJ'
      - key: input_industry_chemical_other_coal_non_energetic_demand
        unit: 'TJ'
