key: industry_ict

groups:
  - header: industry_ict
    items:
      - key: input_industry_ict_electricity_demand
        unit: 'TJ'
  #      entso: |
  #        EB("Final consumption - industry sector - information and communication services - energy use", "Electricity")
