key: industry_metal

groups:
  - header: industry_metal_other
    items:
      - key: input_industry_metal_other_electricity_demand
        unit: 'TJ'
        energy_balance: |
          EB("Final consumption - industry sector - metal other - energy use", "Electricity")
      - key: input_industry_metal_other_network_gas_demand
        unit: 'TJ'
        energy_balance: |
          EB("Final consumption - industry sector - metal other - energy use", "Network gas")
      - key: input_industry_metal_other_steam_hot_water_demand
        unit: 'TJ'
        energy_balance: |
          EB("Final consumption - industry sector - metal other - energy use", "Heat")
      - key: input_industry_metal_other_crude_oil_demand
        unit: 'TJ'
        energy_balance: |
          EB("Final consumption - industry sector - metal other - energy use", "Oil")
      - key: input_industry_metal_other_coal_demand
        unit: 'TJ'
        energy_balance: |
          EB("Final consumption - industry sector - metal other - energy use", "Coal incl lignite and peat") -
          EB("Final consumption - industry sector - metal other - energy use", "Coke oven coke")
