key: industry_residual_heat

groups:
  - header: industry_chemical_residual_heat
    type: slider
    items:
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_processes_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_flue_gasses_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_used_heat_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: industry_refineries_residual_heat
    type: slider
    items:
      - key: industry_useful_demand_for_chemical_refineries_useable_heat_industry_chemicals_refineries_processes_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_refineries_useable_heat_industry_chemicals_refineries_flue_gasses_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_refineries_useable_heat_industry_chemicals_refineries_used_heat_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: industry_fertilizers_residual_heat
    type: slider
    items:
      - key: industry_chemicals_fertilizers_haber_bosch_process_hydrogen_industry_chemicals_fertilizers_processes_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_chemicals_fertilizers_haber_bosch_process_hydrogen_industry_chemicals_fertilizers_flue_gasses_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_chemicals_fertilizers_haber_bosch_process_hydrogen_industry_chemicals_fertilizers_used_heat_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: industry_ict_residual_heat
    type: slider
    items:
      - key: industry_useful_demand_for_other_ict_electricity_industry_other_ict_potential_residual_heat_from_servers_electricity_parent_share
        unit: '%'
      - key: industry_useful_demand_for_other_ict_electricity_industry_other_ict_other_systems_electricity_parent_share
        unit: '%'
        flexible: true
        skip_validation: true