---
# Contains mappings of keys used in ENTSO source CSVs to those used in GQL.
columns:
  AFC: Available for final consumption
  DL: Distribution losses
  EXP: Exports
  FC_E: Final consumption - energy use
  FC_IND_CON_E: Final consumption - industry sector - construction - energy use
  FC_IND_CPC_E: Final consumption - industry sector - chemical and petrochemical - energy use
  FC_IND_E: Final consumption - industry sector - energy use
  FC_IND_FBT_E: Final consumption - industry sector - food, beverages and tobacco - energy use
  FC_IND_IS_E: Final consumption - industry sector - iron and steel - energy use
  FC_IND_MAC_E: Final consumption - industry sector - machinery - energy use
  FC_IND_MQ_E: Final consumption - industry sector - mining and quarrying - energy use
  FC_IND_NE: Final consumption - industry sector - non-energy use
  FC_IND_NFM_E: Final consumption - industry sector - non-ferrous metals - energy use
  FC_IND_NMM_E: Final consumption - industry sector - non-metallic minerals - energy use
  FC_IND_NSP_E: Final consumption - industry sector - not elsewhere specified - energy use
  FC_IND_PPP_E: Final consumption - industry sector - paper, pulp and printing - energy use
  FC_IND_TE_E: Final consumption - industry sector - transport equipment - energy use
  FC_IND_TL_E: Final consumption - industry sector - textile and leather - energy use
  FC_IND_WP_E: Final consumption - industry sector - wood and wood products - energy use
  FC_NE: Final consumption - non-energy use
  FC_OTH_AF_E: Final consumption - other sectors - agriculture and forestry - energy use
  FC_OTH_CP_E: Final consumption - other sectors - commercial and public services - energy use
  FC_OTH_E: Final consumption - other sectors - energy use
  FC_OTH_FISH_E: Final consumption - other sectors - fishing - energy use
  FC_OTH_HH_E: Final consumption - other sectors - households - energy use
  FC_OTH_NE: Final consumption - other sectors - non-energy use
  FC_OTH_NSP_E: Final consumption - other sectors - not elsewhere specified - energy use
  FC_TRA_DAVI_E: Final consumption - transport sector - domestic aviation - energy use
  FC_TRA_DNAVI_E: Final consumption - transport sector - domestic navigation - energy use
  FC_TRA_E: Final consumption - transport sector - energy use
  FC_TRA_NE: Final consumption - transport sector - non-energy use
  FC_TRA_NSP_E: Final consumption - transport sector - not elsewhere specified - energy use
  FC_TRA_PIPE_E: Final consumption - transport sector - pipeline transport - energy use
  FC_TRA_RAIL_E: Final consumption - transport sector - rail - energy use
  FC_TRA_ROAD_E: Final consumption - transport sector - road - energy use
  FEC2020-2030: Final energy consumption (Europe 2020-2030)
  GAE: Gross available energy
  GEP_APCHP: Gross electricity production - autoproducer combined heat and power
  GEP_APE: Gross electricity production - autoproducer electricity only
  GEP_MAPCHP: Gross electricity production - main activity producer combined heat and power
  GEP_MAPE: Gross electricity production - main activity producer electricity only
  GEP: Gross electricity production
  GHP_APCHP: Gross heat production - autoproducer combined heat and power
  GHP_APH: Gross heat production - autoproducer heat only
  GHP_MAPCHP: Gross heat production - main activity producer combined heat and power
  GHP_MAPH: Gross heat production - main activity producer heat only
  GHP: Gross heat production
  GIC: Gross inland consumption
  GIC2020-2030: Gross inland consumption (Europe 2020-2030)
  IMP: Imports
  INTAVI: International aviation
  INTMARB: International maritime bunkers
  NRG_BF_E: Energy sector - blast furnaces - energy use
  NRG_BIOG_E: Energy sector - gasification plants for biogas - energy use
  NRG_BKBPB_E: Energy sector - brown coal briquettes and peat briquettes plants - energy use
  NRG_CL_E: Energy sector - coal liquefaction plants - energy use
  NRG_CM_E: Energy sector - coal mines - energy use
  NRG_CO_E: Energy sector - coke ovens - energy use
  NRG_CPP_E: Energy sector - charcoal production plants - energy use
  NRG_E: Energy sector - energy use
  NRG_EHG_E: Energy sector - electricity and heat generation - energy use
  NRG_GTL_E: Energy sector - gas-to-liquids plants - energy use
  NRG_GW_E: Energy sector - gas works - energy use
  NRG_LNG_E: Energy sector - liquefaction and regasification plants (LNG) - energy use
  NRG_NE: Energy sector - non-energy use
  NRG_NI_E: Energy sector - nuclear industry - energy use
  NRG_NSP_E: Energy sector - not elsewhere specified - energy use
  NRG_OIL_NG_E: Energy sector - oil and natural gas extraction plants - energy use
  NRG_PF_E: Energy sector - patent fuel plants - energy use
  NRG_PR_E: Energy sector - petroleum refineries (oil refineries) - energy use
  NRGSUP: Total energy supply
  PEC2020-2030: Primary energy consumption (Europe 2020-2030)
  PPRD: Primary production
  RCV_RCY: Recovered and recycled products
  STATDIFF: Statistical differences
  STK_CHG: Change in stock
  TI_BF_E: Transformation input - blast furnaces - energy use
  TI_BKBPB_E: Transformation input - brown coal briquettes and peat briquettes plants - energy use
  TI_BNG_E: Transformation input - for blended natural gas - energy use
  TI_CL_E: Transformation input - coal liquefaction plants - energy use
  TI_CO_E: Transformation input - coke ovens - energy use
  TI_CPP_E: Transformation input - charcoal production plants - energy use
  TI_E: Transformation input - energy use
  TI_EHG_APCHP_E: Transformation input - electricity and heat generation - autoproducer combined heat and power - energy use
  TI_EHG_APE_E: Transformation input - electricity and heat generation - autoproducer electricity only - energy use
  TI_EHG_APH_E: Transformation input - electricity and heat generation - autoproducer heat only - energy use
  TI_EHG_DHEP: Transformation input - electricity and heat generation - derived heat for electricity production
  TI_EHG_E: Transformation input - electricity and heat generation - energy use
  TI_EHG_EB: Transformation input - electricity and heat generation - electric boilers
  TI_EHG_EDHP: Transformation input - electricity and heat generation - electrically driven heat pumps
  TI_EHG_EPS: Transformation input - electricity and heat generation - electricity for pumped storage
  TI_EHG_MAPCHP_E: Transformation input - electricity and heat generation - main activity producer combined heat and power - energy use
  TI_EHG_MAPE_E: Transformation input - electricity and heat generation - main activity producer electricity only - energy use
  TI_EHG_MAPH_E: Transformation input - electricity and heat generation - main activity producer heat only - energy use
  TI_GTL_E: Transformation input - gas-to-liquids plants - energy use
  TI_GW_E: Transformation input - gas works - energy use
  TI_LBB_E: Transformation input - liquid biofuels blended - energy use
  TI_NE: Transformation input - non-energy use
  TI_NRG_FC_IND_NE: Transformation input, energy sector and final consumption in industry sector - non-energy use
  TI_NSP_E: Transformation input - not elsewhere specified - energy use
  TI_PF_E: Transformation input - patent fuel plants - energy use
  TI_RPI_BPI_E: Transformation input - refineries and petrochemical industry - backflows from petrochemical industry - energy use
  TI_RPI_DU_E: Transformation input - refineries and petrochemical industry - direct use - energy use
  TI_RPI_E: Transformation input - refineries and petrochemical industry - energy use
  TI_RPI_IT_E: Transformation input - refineries and petrochemical industry - interproduct transfers - energy use
  TI_RPI_PII_E: Transformation input - refineries and petrochemical industry - petrochemical industry intake - energy use
  TI_RPI_PT_E: Transformation input - refineries and petrochemical industry - products transferred - energy use
  TI_RPI_RI_E: Transformation input - refineries and petrochemical industry - refinery intake - energy use
  TO_BF: Transformation output - blast furnaces
  TO_BKBPB: Transformation output - brown coal briquettes and peat briquettes plants
  TO_BNG: Transformation output - blended in natural gas
  TO_CL: Transformation output - coal liquefaction plants
  TO_CO: Transformation output - coke ovens
  TO_CPP: Transformation output - charcoal production plants
  TO_EHG_APCHP: Transformation output - electricity and heat generation - autoproducer combined heat and power
  TO_EHG_APE: Transformation output - electricity and heat generation - autoproducer electricity only
  TO_EHG_APH: Transformation output - electricity and heat generation - autoproducer heat only
  TO_EHG_EB: Transformation output - electricity and heat generation - electric boilers
  TO_EHG_EDHP: Transformation output - electricity and heat generation - electrically driven heat pumps
  TO_EHG_MAPCHP: Transformation output - electricity and heat generation - main activity producer combined heat and power
  TO_EHG_MAPE: Transformation output - electricity and heat generation - main activity producer electricity only
  TO_EHG_MAPH: Transformation output - electricity and heat generation - main activity producer heat only
  TO_EHG_OTH: Transformation output - electricity and heat generation - other sources
  TO_EHG_PH: Transformation output - electricity and heat generation - pumped hydro
  TO_EHG: Transformation output - electricity and heat generation
  TO_GTL: Transformation output - gas-to-liquids plants
  TO_GW: Transformation output - gas works
  TO_LBB: Transformation output - liquid biofuels blended
  TO_NSP: Transformation output - not elsewhere specified
  TO_PF: Transformation output - patent fuel plants
  TO_RPI_BKFLOW: Transformation output - refineries and petrochemical industry - backflows
  TO_RPI_IT: Transformation output - refineries and petrochemical industry - interproduct transfers
  TO_RPI_PIR: Transformation output - refineries and petrochemical industry - petrochemical industry returns
  TO_RPI_PPR: Transformation output - refineries and petrochemical industry - primary product receipts
  TO_RPI_PT: Transformation output - refineries and petrochemical industry - products transferred
  TO_RPI_RO: Transformation output - refineries and petrochemical industry - refinery output
  TO_RPI: Transformation output - refineries and petrochemical industry
  TO: Transformation output
rows:
  BIOE: Bioenergy
  C0000X0350-0370: Solid fossil fuels
  C0110: Anthracite
  C0121: Coking coal
  C0129: Other bituminous coal
  C0210: Sub-bituminous coal
  C0220: Lignite
  C0311: Coke oven coke
  C0312: Gas coke
  C0320: Patent fuel
  C0330: Brown coal briquettes
  C0340: Coal tar
  C0350-0370: Manufactured gases
  C0350: Coke oven gas
  C0360: Gas works gas
  C0371: Blast furnace gas
  C0379: Other recovered gases
  E7000: Electricity
  FE: Fossil energy
  G3000: Natural gas
  H8000: Heat
  N900H: Nuclear heat
  O4000XBIO: Oil and petroleum products
  O4100_TOT: Crude oil
  O4200: Natural gas liquids
  O4300: Refinery feedstocks
  O4400X4410: Additives and oxygenates (excluding biofuel portion)
  O4500: Other hydrocarbons
  O4610: Refinery gas
  O4620: Ethane
  O4630: Liquefied petroleum gases
  O4640: Naphtha
  O4651: Aviation gasoline
  O4652XR5210B: Motor gasoline (excluding biofuel portion)
  O4653: Gasoline-type jet fuel
  O4661XR5230B: Kerosene-type jet fuel (excluding biofuel portion)
  O4669: Other kerosene
  O4671XR5220B: Gas oil and diesel oil (excluding biofuel portion)
  O4680: Fuel oil
  O4691: White spirit and special boiling point industrial spirits
  O4692: Lubricants
  O4693: Paraffin waxes
  O4694: Petroleum coke
  O4695: Bitumen
  O4699: Other oil products
  P1000: Peat and peat products
  P1100: Peat
  P1200: Peat products
  R5110-5150_W6000RI: Primary solid biofuels
  R5160: Charcoal
  R5210B: Blended biogasoline
  R5210P: Pure biogasoline
  R5220B: Blended biodiesels
  R5220P: Pure biodiesels
  R5230B: Blended bio jet kerosene
  R5230P: Pure bio jet kerosene
  R5290: Other liquid biofuels
  R5300: Biogases
  RA000: Renewables and biofuels
  RA100: Hydro
  RA200: Geothermal
  RA300: Wind
  RA410: Solar thermal
  RA420: Solar photovoltaic
  RA500: Tide, wave, ocean
  RA600: Ambient heat (heat pumps)
  S2000: Oil shale and oil sands
  TOTAL: Total
  W6100_6220: Non-renewable waste
  W6100: Industrial waste (non-renewable)
  W6210: Renewable municipal waste
  W6220: Non-renewable municipal waste
row_groups:
  Network gas:
    - Biogases
    - Natural gas
  Coal:
    - Anthracite
    - Coking coal
    - Sub-bituminous coal
    - Lignite
    - Patent fuel
    - Coke oven coke
    - Gas coke
    - Coal tar
    - Brown coal briquettes
    - Peat and peat products
  Coal gas:
    - Coke oven gas
    - Blast furnace gas
    - Other recovered gases
  Crude oil aggregated:
    - Crude oil
    - Natural gas liquids
    - Refinery feedstocks
    - Additives and oxygenates (excluding biofuel portion)
    - Other hydrocarbons
    - Refinery gas
    - Ethane
    - Liquefied petroleum gases
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
    - Gas oil and diesel oil (excluding biofuel portion)
    - Fuel oil
    - Naphtha
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Bitumen
    - Paraffin waxes
    - Petroleum coke
    - Other oil products
  Kerosene:
    - Kerosene-type jet fuel (excluding biofuel portion)
    - Other kerosene
  Bio-kerosene:
    - Pure bio jet kerosene
    - Blended bio jet kerosene
  Bio oil:
    - Pure biogasoline
    - Other liquid biofuels
  Other oil:
    - Crude oil
    - Other hydrocarbons
    - Additives and oxygenates (excluding biofuel portion)
    - Refinery feedstocks
    - Natural gas liquids
    - Ethane
    - Motor gasoline (excluding biofuel portion)
    - Aviation gasoline
    - Gasoline-type jet fuel
    - Fuel oil
    - Naphtha
    - White spirit and special boiling point industrial spirits
    - Lubricants
    - Bitumen
    - Paraffin waxes
    - Petroleum coke
    - Other oil products
