---
households_final_demand_electricity_demand:
  legend_type: dynamic
  unit: 'kWh'
  color_stops:
    - "#00FF00"
    - "#FF0000"
  layers:
    - provinces
    - municipalities
    - districts
    - neighborhoods

households_final_demand_network_gas_demand:
  legend_type: dynamic
  unit: 'm3'
  color_stops:
    - "#00FF00"
    - "#FF0000"
  layers:
    - provinces
    - municipalities
    - districts
    - neighborhoods

number_of_inhabitants:
  legend_type: dynamic
  unit: '#'
  scale: log10
  color_stops:
    - "#009cff"
    - "#000000"
  layers:
    - provinces
    - municipalities
    - districts
    - neighborhoods

number_of_cars:
  legend_type: dynamic
  unit: '#'
  scale: log10
  color_stops:
    - "#009cff"
    - "#000000"
  layers:
    - provinces
    - municipalities
    - districts
    - neighborhoods

roof_surface_available_for_pv:
  legend_type: dynamic
  unit: '#'
  scale: log10
  color_stops:
    - "#FF0000"
    - "#00FF00"
  layers:
    - provinces
    - municipalities
    - districts
    - neighborhoods

potential_heat_wko_neighborhood:
  legend_type: static
  layers:
    - potential_heat_wko_neighborhood

bag:
  legend_type: none
  layers:
    - bag
