area:
  - area_advanced
households:
  - households_energy_demand
  - households_energy_supply
  - households_advanced
buildings:
  - buildings_energy_demand
  - buildings_energy_supply
  - buildings_advanced
transport:
  - transport_road_transport
  - transport_rail_transport
  - transport_ship_transport
  - transport_plane_transport
  - transport_advanced
agriculture:
industry:
  - industry_metal
  - industry_chemical
  - industry_food
  - industry_paper
  - industry_ict
  - industry_other
energy:
  - energy_renewable_electricity_production
  - energy_fossil_electricity_production
  - energy_heat_production
  - energy_full_load_hours
other:
