key: energy_heat_production
groups:
  - header: energy_heat
    items:
      - key: input_energy_heat_burner_wood_pellets_production
        unit: 'TJ'
      - key: input_energy_heat_well_geothermal_production
        unit: 'TJ'
      - key: input_energy_heat_burner_waste_mix_production
        unit: 'TJ'
      - key: input_energy_heat_burner_hydrogen_production
        unit: 'TJ'
      - key: input_energy_heat_solar_thermal_production
        unit: 'TJ'
      - key: input_energy_heat_heatpump_water_water_electricity_production
        unit: 'TJ'
      - key: input_energy_heat_burner_network_gas_production
        unit: 'TJ'
      - key: input_energy_heat_burner_coal_production
        unit: 'TJ'
      - key: input_energy_heat_burner_crude_oil_production
        unit: 'TJ'

  - header: energy_heat_distribution_loss
    items:
      - key: energy_heat_distribution_loss_demand
        unit: 'TJ'

  - header: industry_chemical_residual_heat
    type: slider
    items:
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_processes_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_flue_gasses_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_used_heat_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: industry_refineries_residual_heat
    type: slider
    items:
      - key: industry_useful_demand_for_chemical_refineries_useable_heat_industry_chemicals_refineries_processes_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_refineries_useable_heat_industry_chemicals_refineries_flue_gasses_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_refineries_useable_heat_industry_chemicals_refineries_used_heat_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: industry_fertilizers_residual_heat
    type: slider
    items:
      - key: industry_chemicals_fertilizers_haber_bosch_process_hydrogen_industry_chemicals_fertilizers_processes_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_chemicals_fertilizers_haber_bosch_process_hydrogen_industry_chemicals_fertilizers_flue_gasses_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_chemicals_fertilizers_haber_bosch_process_hydrogen_industry_chemicals_fertilizers_used_heat_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: industry_ict_residual_heat
    type: slider
    items:
      - key: industry_useful_demand_for_other_ict_electricity_industry_other_ict_potential_residual_heat_from_servers_electricity_parent_share
        unit: '%'
      - key: industry_useful_demand_for_other_ict_electricity_industry_other_ict_other_systems_electricity_parent_share
        unit: '%'
        flexible: true
        skip_validation: true

  - header: energy_heat_import
    items:
      - key: energy_import_heat_demand
        unit: 'TJ'
