key: energy_fossil_electricity_production
groups:
  - header: energy_electricity_coal
    items:
      - key: input_energy_power_ultra_supercritical_coal_production
        unit: 'TJ'
      - key: input_energy_power_supercritical_coal_production
        unit: 'TJ'
      - key: input_energy_power_combined_cycle_coal_production
        unit: 'TJ'
      - key: input_energy_power_ultra_supercritical_cofiring_coal_production
        unit: 'TJ'
      - key: input_energy_power_combined_cycle_ccs_coal_production
        unit: 'TJ'
      - key: input_energy_power_combined_cycle_ccs_coal_production
        unit: 'TJ'
      - key: input_energy_power_ultra_supercritical_ccs_coal_production
        unit: 'TJ'
      - key: input_energy_chp_ultra_supercritical_coal_production
        unit: 'TJ'
      - key: input_energy_chp_ultra_supercritical_cofiring_coal_production
        unit: 'TJ'

  - header: energy_electricity_gas
    items:
      - key: input_energy_power_ultra_supercritical_network_gas_production
        unit: 'TJ'
      - key: input_energy_power_turbine_network_gas_production
        unit: 'TJ'
      - key: input_energy_power_engine_network_gas_production
        unit: 'TJ'
      - key: input_energy_power_combined_cycle_network_gas_production
        unit: 'TJ'
      - key: input_energy_power_combined_cycle_ccs_network_gas_production
        unit: 'TJ'
      - key: input_energy_chp_combined_cycle_network_gas_production
        unit: 'TJ'

  - header: energy_electricity_other_fossil
    items:
      - key: input_energy_power_nuclear_gen2_uranium_oxide_production
        unit: 'TJ'
      - key: input_energy_power_nuclear_gen3_uranium_oxide_production
        unit: 'TJ'
      - key: input_energy_power_ultra_supercritical_crude_oil_production
        unit: 'TJ'
      - key: input_energy_power_engine_diesel_production
        unit: 'TJ'