key: energy_fossil_electricity_production
groups:
  - header: energy_electricity_coal
    items:
      - key: input_energy_power_ultra_supercritical_coal_production
        unit: 'TJ'
        entso: |
          EB("Coal pulverized", "Electricity")
      - key: input_energy_power_supercritical_coal_production
        unit: 'TJ'
        entso: |
          EB("Coal conventional", "Electricity")
      - key: input_energy_power_combined_cycle_coal_production
        unit: 'TJ'
        entso: |
          EB("Coal IGCC", "Electricity")
      - key: input_energy_power_ultra_supercritical_cofiring_coal_production
        unit: 'TJ'
        entso: |
          EB("Coal pulverized with biomass co-firing", "Electricity")
      - key: input_energy_power_combined_cycle_ccs_coal_production
        unit: 'TJ'
        entso: |
          EB("Coal IGCC CCS", "Electricity")
      - key: input_energy_power_ultra_supercritical_ccs_coal_production
        unit: 'TJ'
        # entso: |
        #   EB("Coal pulverized CCS", "Electricity")
      - key: input_energy_chp_ultra_supercritical_coal_production
        unit: 'TJ'
      - key: input_energy_chp_ultra_supercritical_cofiring_coal_production
        unit: 'TJ'
      - key: input_energy_power_supercritical_ccs_waste_mix_production
        unit: 'TJ'
        # entso: |
        #   EB("Waste incinerator CCS", "Electricity")
      - key: input_energy_power_ultra_supercritical_lignite_production
        unit: 'TJ'
        entso: |
          EB("Lignite", "Electricity")
      - key: input_energy_power_ultra_supercritical_oxyfuel_ccs_lignite_production
        unit: 'TJ'
        entso: |
          EB("Lignite CCS", "Electricity")

  - header: energy_electricity_gas
    items:
      - key: input_energy_power_ultra_supercritical_network_gas_production
        unit: 'TJ'
        entso: |
          EB("Gas conventional", "Electricity")
      - key: input_energy_power_turbine_network_gas_production
        unit: 'TJ'
        entso: |
          EB("Gas turbine", "Electricity")
      - key: input_energy_power_engine_network_gas_production
        unit: 'TJ'
        entso: |
          EB("Gas combustion engine", "Electricity")
      - key: input_energy_power_combined_cycle_network_gas_production
        unit: 'TJ'
        entso: |
          EB("Gas CCGT", "Electricity")
      - key: input_energy_power_combined_cycle_ccs_network_gas_production
        unit: 'TJ'
        entso: |
          EB("Gas CCGT CCS", "Electricity")
      - key: input_energy_chp_combined_cycle_network_gas_production
        unit: 'TJ'
      - key: input_energy_chp_local_engine_network_gas_production
        unit: 'TJ'

  - header: energy_electricity_other_fossil
    items:
      - key: input_energy_power_nuclear_gen2_uranium_oxide_production
        unit: 'TJ'
        entso: |
          EB("Nuclear conventional", "Electricity")
      - key: input_energy_power_nuclear_gen3_uranium_oxide_production
        unit: 'TJ'
        entso: |
          EB("Nuclear 3rd generation", "Electricity")
      - key: input_energy_power_ultra_supercritical_crude_oil_production
        unit: 'TJ'
        entso: |
          EB("Oil-fired power plant", "Electricity")
      - key: input_energy_power_engine_diesel_production
        unit: 'TJ'
        # entso: |
        #   EB("Diesel generator", "Electricity")
