key: energy_heat_production

groups:
  # Aquathermal potentials
  - header: energy_aquathermal_potentials
    items:
        - key: aquathermal_potential_for_surface_water
          unit: 'TJ'
        - key: aquathermal_potential_for_waste_water
          unit: 'TJ'
        - key: aquathermal_potential_for_drink_water
          unit: 'TJ'

  # Biomass
  - header: energy_heat_wood_pellets
    items:
      - key: input_energy_heat_burner_ht_wood_pellets_production
        unit: 'TJ'
      - key: input_energy_heat_burner_mt_wood_pellets_production
        unit: 'TJ'

  # Coal
  - header: energy_heat_coal
    items:
      - key: input_energy_heat_burner_ht_coal_production
        unit: 'TJ'
      - key: input_energy_heat_burner_mt_coal_production
        unit: 'TJ'

  # Crude oil
  - header: energy_heat_crude_oil
    items:
      - key: input_energy_heat_burner_ht_crude_oil_production
        unit: 'TJ'
      - key: input_energy_heat_burner_mt_crude_oil_production
        unit: 'TJ'

  # Electric
  - header: energy_heat_electricity
    items:
      - key: input_energy_heat_heatpump_water_water_ht_electricity_production
        unit: 'TJ'
      - key: input_energy_heat_heatpump_water_water_mt_electricity_production
        unit: 'TJ'
      - key: input_energy_heat_heatpump_water_water_lt_electricity_production
        unit: 'TJ'
      - key: input_energy_heat_boiler_ht_electricity_production
        unit: 'TJ'
      - key: input_energy_heat_boiler_mt_electricity_production
        unit: 'TJ'
      - key: input_energy_heat_boiler_lt_electricity_production
        unit: 'TJ'

  # Geothermal
  - header: energy_heat_geothermal
    items:
      - key: input_energy_heat_well_deep_ht_geothermal_production
        unit: 'TJ' 
      - key: input_energy_heat_well_deep_mt_geothermal_production
        unit: 'TJ'
      - key: input_energy_heat_well_shallow_heatpump_mt_geothermal_production
        unit: 'TJ'
      - key: input_energy_heat_well_shallow_lt_geothermal_production
        unit: 'TJ'

  # Hydrogen
  - header: energy_heat_hydrogen
    items:
      - key: input_energy_heat_burner_ht_hydrogen_production
        unit: 'TJ'
      - key: input_energy_heat_burner_mt_hydrogen_production
        unit: 'TJ'
      - key: input_energy_heat_burner_lt_hydrogen_production
        unit: 'TJ'

  # Network gas
  - header: energy_heat_network_gas
    items:
      - key: input_energy_heat_burner_ht_network_gas_production
        unit: 'TJ'
      - key: input_energy_heat_burner_mt_network_gas_production
        unit: 'TJ'

  # Solar thermal
  - header: energy_heat_solar_thermal
    items:
      - key: input_energy_heat_solar_ht_solar_thermal_production
        unit: 'TJ'
      - key: input_energy_heat_solar_mt_solar_thermal_production
        unit: 'TJ'
      - key: input_energy_heat_solar_lt_solar_thermal_production
        unit: 'TJ'

  # Waste mix
  - header: energy_heat_waste_mix
    items:
      - key: input_energy_heat_burner_ht_waste_mix_production
        unit: 'TJ'
      - key: input_energy_heat_burner_mt_waste_mix_production
        unit: 'TJ'
  
  # Import
  - header: energy_heat_import
    items:
      - key: energy_heat_import_ht_steam_hot_water_demand
        unit: 'TJ'
      - key: energy_heat_import_mt_steam_hot_water_demand
        unit: 'TJ'
      - key: energy_heat_import_lt_steam_hot_water_demand
        unit: 'TJ'
