key: energy_heat_production
groups:
  - header: energy_heat_renewable
    items:
      - key: input_energy_heat_burner_wood_pellets_production
        unit: 'TJ'
        entso: |
          EB("Biomass heater - residential", "Heat")
      - key: input_energy_heat_well_geothermal_production
        unit: 'TJ' 
        entso: |
          EB("Geothermal - residential", "Heat")
      - key: input_energy_heat_burner_waste_mix_production
        unit: 'TJ'
        entso: |
          EB("Waste heater - residential", "Heat")
      - key: input_energy_heat_burner_hydrogen_production
        unit: 'TJ'
        entso: 0.0
      - key: input_energy_heat_solar_thermal_production
        unit: 'TJ'
        entso: |
          EB("Solar thermal - residential", "Heat")
      - key: input_energy_heat_heatpump_water_water_electricity_production
        unit: 'TJ'
        entso: 0.0
        
  - header: energy_heat_fossil
    items:
      - key: input_energy_heat_burner_network_gas_production
        unit: 'TJ'
        entso: |
          EB("Gas heater - residential", "Heat")
      - key: input_energy_heat_burner_coal_production
        unit: 'TJ'
        entso: |
          EB("Coal heater - industrial", "Heat")
      - key: input_energy_heat_burner_crude_oil_production
        unit: 'TJ'
        entso: |
          EB("Oil heater - industrial", "Heat")

  - header: energy_heat_import
    items:
      - key: energy_import_heat_demand
        unit: 'TJ'

  - header: energy_heat_distribution_loss
    items:
      - key: energy_heat_distribution_loss_demand
        unit: 'TJ'
        entso: |
          EB("Distribution losses", "Heat")
